"""Generate 900 more SaaS apps to bring total to 1000."""
import os
import sys
from pathlib import Path

BASE = Path(__file__).parent

# Reuse generators from full-stack script
sys.path.insert(0, str(BASE))
import importlib.util
spec = importlib.util.spec_from_file_location("fs", BASE / "_generate_fs.py")
fs = importlib.util.module_from_spec(spec)
spec.loader.exec_module(fs)
build = fs.build

# Categories with templates — each generates 100 apps
CATEGORY_TEMPLATES = [
    ("AI Tools", [
        ("Synth", "AI content synthesizer for marketing teams",
         "Generate on-brand copy from a single prompt. Synth learns your voice and produces variations.",
         "Voice-trained generation", "Variant A/B testing", "Plagiarism check"),
        ("Promptly", "Prompt engineering workspace",
         "Version, test, and ship prompts. Promptly tracks performance across models.",
         "Prompt versioning", "Multi-model eval", "Cost tracking"),
        ("AgentForge", "Build and deploy AI agents",
         "Drag-drop agent builder with tools, memory, and guardrails. AgentForge ships to Slack/web/API.",
         "Visual agent builder", "Tool registry", "Guardrails + evals"),
        ("RagStack", "Production RAG in minutes",
         "Upload docs, get a chat-with-your-data API. RagStack handles chunking, embedding, citations.",
         "Document ingestion", "Hybrid search", "Citation tracking"),
        ("EmbedLab", "Embedding model evaluation",
         "Compare embedding models on YOUR data. EmbedLab scores recall, latency, cost.",
         "Multi-model benchmarks", "Latency profiling", "Cost forecasting"),
        ("FineTune", "No-code fine-tuning studio",
         "Fine-tune open models on your data with a few clicks. FineTune handles GPU, eval, deploy.",
         "Visual dataset builder", "Multi-GPU training", "Eval dashboards"),
        ("LLMRouter", "Smart LLM routing",
         "Route prompts to the right model based on cost, latency, quality. LLMRouter saves 60%+ on bills.",
         "Cost-aware routing", "Fallback chains", "Quality scoring"),
        ("VectorVault", "Managed vector database",
         "Drop-in Pinecone alternative. VectorVault handles sharding, replicas, snapshots.",
         "Sharded storage", "Snapshot/restore", "Multi-tenant"),
        ("ChatPilot", "AI chat widget for any site",
         "One-line embed. ChatPilot gives every site a GPT trained on its content.",
         "One-line embed", "Source citations", "Lead capture mode"),
        ("DocuParse", "Document AI for invoices/contracts",
         "Extract structured data from PDFs/contracts/invoices. DocuParse returns JSON with confidence.",
         "Schema extraction", "Confidence scoring", "Human review UI"),
        ("VoiceAI", "Voice agent platform",
         "Build phone agents that sound human. VoiceAI handles STT/TTS, tools, transfers.",
         "Realtime STT/TTS", "Tool calling", "Call transfer"),
        ("VisionLab", "Computer vision labeling",
         "Label images/videos 5x faster with AI assist. VisionLab exports to YOLO/COCO.",
         "AI-assisted labeling", "Multi-format export", "QA workflows"),
        ("Transcripter", "Long-form transcription",
         "Transcribe 4-hour videos with speaker diarization, chapter detection, and search.",
         "Speaker diarization", "Chapter detection", "Searchable archive"),
        ("SummarizeIt", "URL/article summarizer API",
         "Drop-in summarization API. SummarizeIt handles news, blogs, papers, videos.",
         "Multi-format input", "Length control", "Bullet/JSON modes"),
        ("TranslatePro", "Context-aware translation",
         "More than literal translation. TranslatePro preserves tone, glossary, brand voice.",
         "Glossary enforcement", "Tone control", "Side-by-side review"),
        ("SentimentAI", "Real-time sentiment analysis",
         "Track sentiment across reviews, support tickets, social. SentimentAI surfaces trends.",
         "Real-time stream", "Trend detection", "Topic clustering"),
        ("Moderatly", "Content moderation AI",
         "Moderate UGC at scale. Moderatly flags toxic, NSFW, spam with explainable reasons.",
         "Multi-class classification", "Explainable flags", "Human review queue"),
        ("PersonaForge", "Synthetic user personas",
         "Generate research-grade personas for product testing. PersonaForge simulates behavior.",
         "Persona generation", "Behavior simulation", "Survey response"),
        ("CoachAI", "Personal AI coach builder",
         "Build coaches for fitness, study, sales. CoachAI combines LLM + structured programs.",
         "Program builder", "Progress tracking", "Multi-modal input"),
        ("CodePilot", "AI code completion server",
         "Self-hosted Copilot alternative. CodePilot runs on your infra with your models.",
         "Self-hosted", "Multi-model support", "Codebase indexing"),
    ] * 5),  # 100 apps

    ("Content Creation", [
        ("BlogBot", "AI blog writer",
         "Long-form blog posts from a topic. BlogBot does research, outline, draft, polish.",
         "Auto-research", "SEO optimization", "Multi-format export"),
        ("VideoScript", "YouTube script generator",
         "Hooks, structure, B-roll notes. VideoScript writes videos that retain viewers.",
         "Retention hooks", "B-roll prompts", "Thumbnail ideas"),
        ("CaptionCraft", "Social caption generator",
         "On-brand captions for IG/TikTok/LinkedIn. CaptionCraft learns your style.",
         "Multi-platform", "Brand voice", "Hashtag research"),
        ("NewsletterAI", "Newsletter writing assistant",
         "Curate, draft, and ship newsletters. NewsletterAI learns from your best editions.",
         "Curation engine", "Subject-line scoring", "Send-time optimization"),
        ("PodcastScript", "Podcast outline + show notes",
         "Outline episodes, generate show notes, social clips. PodcastScript ships episodes faster.",
         "Episode outlines", "Show notes", "Clip extraction"),
        ("EbookForge", "Lead-magnet ebook generator",
         "50-page ebook from a topic. EbookForge writes, designs, and exports PDF.",
         "Auto-research", "PDF design", "Lead capture"),
        ("AdCopy", "Ad copy generator",
         "Google/Meta/LinkedIn ads that convert. AdCopy tests 100 variants.",
         "Multi-platform", "Variant testing", "Performance prediction"),
        ("ImagePrompt", "Midjourney prompt engineer",
         "Turn rough ideas into refined prompts. ImagePrompt boosts image quality 10x.",
         "Style library", "Negative prompts", "Upscale workflow"),
        ("StorySparrow", "Fiction writing assistant",
         "Plot, character, scene — StorySparrow helps authors finish novels.",
         "Plot outliner", "Character bibles", "Scene-level edits"),
        ("WhitePaper", "B2B whitepaper generator",
         "Long-form, sourced, persuasive. WhitePaper ships thought leadership in days.",
         "Source citation", "Executive summary", "Design export"),
        ("CaseStudy", "Customer case study builder",
         "Interview customers, generate case studies. CaseStudy ships social-proof assets.",
         "Interview transcription", "Quote extraction", "Multi-format"),
        ("PressKit", "Press release + media kit",
         "PR templates + media contact DB. PressKit ships announcements fast.",
         "Template library", "Media contacts", "Distribution tracking"),
        ("BrandStory", "Brand storytelling platform",
         "Mission, vision, manifesto, history. BrandStory writes your origin story.",
         "Story frameworks", "Multi-language", "Asset library"),
        ("Scriptly", "Screenplay formatting",
         "Industry-standard screenplay formatting in the browser. Scriptly exports PDF.",
         "Auto-format", "Scene navigation", "Production reports"),
        ("LyricLab", "Songwriting assistant",
         "Melody-aware lyric suggestions. LyricLab rhymes, scans, and structures.",
         "Rhyme dictionary", "Meter scanner", "Chord suggestions"),
        ("TweetBeam", "Twitter thread composer",
         "Long-form threads with hooks. TweetBeam optimizes for engagement.",
         "Hook templates", "Engagement prediction", "Schedule posts"),
        ("LinkedinPro", "LinkedIn post generator",
         "Authority-building posts. LinkedinPro learns your voice and topics.",
         "Voice training", "Topic calendar", "Engagement scoring"),
        ("CourseScript", "Online course script writer",
         "Module-by-module scripts with visuals. CourseScript ships courses in weeks.",
         "Module templates", "Visual storyboards", "Quiz generation"),
        ("SpeechWriter", "Speech writing assistant",
         "Keynotes, weddings, TED-style talks. SpeechWriter times delivery.",
         "Timing tracker", "Audience analysis", "Delivery notes"),
        ("ComicForge", "Comic book creator",
         "Panel-by-panel storyboard with consistent characters. ComicForge exports print-ready.",
         "Character consistency", "Panel layouts", "Print export"),
    ] * 5),  # 100 apps

    ("Customer Support", [
        ("HelpDeskAI", "AI-first helpdesk",
         "Resolve tickets before they hit a human. HelpDeskAI deflects 60% with smart replies.",
         "Smart reply", "Auto-deflection", "Agent assist"),
        ("ChatSupport", "Live chat with AI assist",
         "Drop-in chat with AI co-pilot for agents. ChatSupport cuts response time in half.",
         "Agent co-pilot", "Canned responses", "Visitor insights"),
        ("TicketTriage", "Auto-ticket classification",
         "Route, prioritize, and tag tickets. TicketTriage learns from past resolutions.",
         "Auto-routing", "Priority scoring", "Tag suggestions"),
        ("KbSearch", "Knowledge base search",
         "AI-powered KB that understands intent. KbSearch returns the right article.",
         "Semantic search", "Gap detection", "Article scoring"),
        ("VoiceSupport", "Phone support with AI",
         "AI answers calls, escalates to humans. VoiceSupport reduces call volume 40%.",
         "Realtime STT/TTS", "Smart escalation", "Call summaries"),
        ("ReturnsFlow", "Returns automation",
         "Self-serve returns portal. ReturnsFlow handles RMA, refunds, exchanges.",
         "RMA generator", "Refund automation", "Exchange suggestions"),
        ("FeedbackLoop", "Customer feedback aggregator",
         "NPS, CSAT, reviews in one inbox. FeedbackLoop surfaces themes with AI.",
         "Multi-channel inbox", "Theme clustering", "Action routing"),
        ("MacroMagic", "Response template manager",
         "Team-shared macros with variables. MacroMagic measures usage and quality.",
         "Variable substitution", "Usage analytics", "Version history"),
        ("StatusAI", "Customer-facing status page",
         "Branded status page with incident timelines. StatusAI sends proactive updates.",
         "Incident timelines", "Subscriber updates", "Component status"),
        ("SurveyPulse", "CSAT/NPS surveys",
         "Trigger surveys at the right moment. SurveyPulse correlates with churn.",
         "Smart triggers", "Churn correlation", "Multi-channel"),
        ("OutboundAI", "Proactive outreach",
         "Reach out before customers churn. OutboundAI drafts and schedules messages.",
         "Churn prediction", "Message drafting", "A/B testing"),
        ("QueueMaster", "Smart queue management",
         "Skills-based routing with SLA tracking. QueueMaster cuts wait times.",
         "Skills routing", "SLA tracking", "Agent load balancing"),
        ("MacroAI", "AI macro suggestions",
         "Suggests the right macro mid-reply. MacroAI learns from past tickets.",
         "Inline suggestions", "Auto-expansion", "Quality scoring"),
        ("SentimentScore", "Real-time sentiment",
         "Detect angry customers in real-time. SentimentScore flags escalations early.",
         "Real-time alerts", "Trend tracking", "Agent coaching"),
        ("ChatInsights", "Chat analytics dashboard",
         "Volume, deflection, CSAT, response time. ChatInsights tells the full story.",
         "Volume metrics", "Deflection rate", "Custom reports"),
        ("HelpCenter", "Self-serve portal builder",
         "Drag-drop help center with AI search. HelpCenter ships in hours.",
         "Visual editor", "AI search", "Multi-brand"),
        ("OnboardFlow", "Customer onboarding flows",
         "Trigger checklists in-product. OnboardFlow lifts activation 30%.",
         "In-product checklists", "Trigger engine", "Outcome tracking"),
        ("TicketMacro", "Template library",
         "Searchable macro library with usage stats. TicketMacro saves hours per agent.",
         "Full-text search", "Usage analytics", "Team sharing"),
        ("SupportBot", "Website chatbot",
         "GPT-powered chatbot trained on your site + KB. SupportBot deflects 70%.",
         "Knowledge training", "Lead capture", "Handoff to human"),
        ("RefundFlow", "Refund automation",
         "Approve, issue, and reconcile refunds. RefundFlow enforces policy.",
         "Policy engine", "Approval workflows", "Reconciliation"),
    ] * 5),  # 100 apps

    ("Project Management", [
        ("Sprintly", "Sprint planning for agile teams",
         "Backlog grooming, sprint planning, retros — all in one. Sprintly replaces Jira for SMBs.",
         "Sprint planning", "Retrospectives", "Velocity charts"),
        ("Kanbanly", "Visual kanban with WIP limits",
         "Drag-drop kanban with auto-WIP. Kanbanly prevents overload.",
         "WIP limits", "Swimlanes", "Cycle time"),
        ("Roadmaply", "Product roadmap builder",
         "Visual roadmaps with stakeholder sharing. Roadmaply replaces Aha!",
         "Timeline views", "Stakeholder portals", "Status updates"),
        ("BugTrack", "Lightweight bug tracker",
         "Capture, triage, fix bugs. BugTrack is Jira without the bloat.",
         "Triage queue", "Severity scoring", "Fix verification"),
        ("Ganttly", "Gantt chart for SMBs",
         "Drag-drop Gantt with dependencies. Ganttly replaces MS Project for small teams.",
         "Dependency tracking", "Critical path", "Resource leveling"),
        ("RetrosAI", "AI retrospective assistant",
         "Suggests themes from raw retro notes. RetrosAI saves PM hours.",
         "Theme extraction", "Action item tracking", "Sentiment trends"),
        ("EstimatePro", "Planning poker + estimation",
         "Async estimation rounds with consensus. EstimatePro kills meeting overhead.",
         "Planning poker", "Calibration tracking", "Velocity trends"),
        ("StandupBot", "Async standup collector",
         "Collects updates in Slack/Teams. StandupBot ships a digest to managers.",
         "Multi-channel", "Blocker surfacing", "Manager digests"),
        ("Timesheetly", "Lightweight time tracking",
         "Project time tracking with reporting. Timesheetly replaces Toggl for teams.",
         "Project budgets", "Approval workflow", "Invoice export"),
        ("Capacityly", "Team capacity planner",
         "Allocate work to people without overloading. Capacityly prevents burnout.",
         "Capacity forecasts", "Skill matching", "Burnout alerts"),
        ("Backlogly", "Backlog management",
         "Prioritize, estimate, and groom backlogs. Backlogly integrates with Linear/Jira.",
         "WSJF scoring", "Two-way sync", "Stakeholder views"),
        ("Milestone", "Milestone tracking",
         "Track high-level milestones across teams. Milestone replaces spreadsheets.",
         "Cross-team views", "Slack updates", "Risk flagging"),
        ("ReleaseOps", "Release management",
         "Coordinate releases across services. ReleaseOps ships on time.",
         "Release calendar", "Dependency graph", "Rollback plans"),
        ("RiskLog", "Risk register + heatmap",
         "Track project risks with mitigation. RiskLog surfaces what matters.",
         "Risk heatmap", "Mitigation tracking", "Review cadence"),
        ("ScopeGuard", "Scope creep detector",
         "Detects when projects drift from scope. ScopeGuard alerts PMs early.",
         "Scope drift alerts", "Change tracking", "Stakeholder reports"),
        ("VendorPM", "Vendor project tracking",
         "Track deliverables from external vendors. VendorPM prevents missed deadlines.",
         "Deliverable tracking", "SLA monitoring", "Approval flows"),
        ("ResourcePlan", "Resource planning",
         "Allocate people to projects by skill. ResourcePlan prevents conflicts.",
         "Skill matrix", "Allocation rules", "Conflict detection"),
        ("SpecWriter", "PRD/PR/FAQ generator",
         "AI-assisted spec writing. SpecWriter follows Teresa Torres / Marty Cagan formats.",
         "Template library", "AI assistance", "Version control"),
        ("RetroBoard", "Digital retro board",
         "Mad/Sad/Glad, 4Ls, KALM — RetroBoard has them all.",
         "Multiple formats", "Anonymous mode", "Action item tracking"),
        ("Kickoffly", "Project kickoff facilitator",
         "Templates and agendas for project kickoffs. Kickoffly ensures alignment.",
         "Kickoff templates", "Stakeholder matrix", "Goals worksheet"),
    ] * 5),  # 100 apps

    ("Data & BI", [
        ("DataPipe", "No-code data pipeline",
         "ETL/ELT without code. DataPipe connects 200+ sources to warehouses.",
         "200+ connectors", "Visual transforms", "Scheduling"),
        ("MetricBase", "Metrics layer for BI",
         "Define metrics once, use everywhere. MetricBase stops metric chaos.",
         "Semantic layer", "Version control", "Multi-tool"),
        ("Dashly", "Dashboard in minutes",
         "Drag-drop dashboards on any SQL. Dashly beats Looker for SMBs.",
         "Drag-drop UI", "SQL flexibility", "Embeddable"),
        ("QueryPad", "SQL notebook",
         "Notebook-style SQL with sharing. QueryPad replaces Mode for analysts.",
         "Notebook UI", "Schedule queries", "Visualization"),
        ("ETLFly", "Serverless ETL",
         "Write transforms in Python, deploy as jobs. ETLFly handles infra.",
         "Serverless runtime", "Python-native", "Auto-scaling"),
        ("SchemaSync", "Schema diff and sync",
         "Diff and sync schemas across environments. SchemaSync prevents prod drift.",
         "Schema diff", "Approval workflow", "Migration scripts"),
        ("LineageMap", "Data lineage visualizer",
         "See where every column came from. LineageMap builds trust in data.",
         "Column-level lineage", "Impact analysis", "Auto-discovery"),
        ("QualityCheck", "Data quality monitoring",
         "Anomaly detection, freshness checks, schema tests. QualityCheck catches issues early.",
         "Anomaly detection", "Freshness SLAs", "Slack alerts"),
        ("ReverseETL", "Sync warehouse to SaaS",
         "Push warehouse data to CRM/marketing tools. ReverseETL closes the loop.",
         "Multi-destination", "Sync monitoring", "Identity resolution"),
        ("WarehouseHub", "Multi-warehouse query",
         "Query Snowflake/BQ/Redshift from one place. WarehouseHub unifies analytics.",
         "Federated query", "Cost optimization", "Caching"),
        ("CostGuard", "Warehouse cost monitoring",
         "Tag-based cost allocation + alerts. CostGuard cuts cloud bills 30%.",
         "Tag-based attribution", "Budget alerts", "Optimization tips"),
        ("DataShare", "Secure data sharing",
         "Share datasets with partners without copies. DataShare is clean rooms for SMBs.",
         "Clean room UI", "Access policies", "Audit logs"),
        ("ReportKit", "Scheduled reports",
         "Schedule and ship PDF/Slack reports. ReportKit replaces Crystal Reports.",
         "Visual designer", "Multi-format export", "Subscriber lists"),
        ("ForecastAI", "Time-series forecasting",
         "Forecast sales/demand/inventory with AI. ForecastAI is Prophet in a UI.",
         "Auto-ML", "Confidence intervals", "Scenario planning"),
        ("ABTestly", "A/B test analyzer",
         "Statistical engine with Bayesian options. ABTestly stops p-hacking.",
         "Bayesian stats", "Sequential testing", "CUPED variance reduction"),
        ("CohortAI", "Auto cohort discovery",
         "Find cohorts that retain. CohortAI uses ML to surface insights.",
         "ML cohorts", "Retention curves", "Export to CRM"),
        ("EventLake", "Event store for analytics",
         "Schema-flexible event store with replay. EventLake replaces Kinesis for SMBs.",
         "Replay capability", "Schema evolution", "Cost-effective"),
        ("BIStudio", "White-label BI",
         "Embed analytics in your product. BIStudio is Mode for SaaS.",
         "White-label UI", "Row-level security", "Multi-tenant"),
        ("MetricAlert", "Metric-based alerting",
         "Alert on any metric, any threshold. MetricAlert routes to Slack/PagerDuty.",
         "Multi-channel routing", "Anomaly alerts", "On-call schedules"),
        ("SQLForm", "SQL form builder",
         "Forms backed by SQL. SQLForm turns analysts into app builders.",
         "Form designer", "SQL backend", "Webhook output"),
    ] * 5),  # 100 apps

    ("Security", [
        ("VaultKey", "Secrets management",
         "Centralized secrets with versioning. VaultKey replaces HashiCorp for SMBs.",
         "Version history", "Auto-rotation", "Audit logs"),
        ("SSOReady", "SSO/SAML for B2B SaaS",
         "Drop-in SSO/SAML/SCIM. SSOReady ships enterprise features in days.",
         "SAML/SCIM", "Just-in-time provisioning", "Multi-tenant"),
        ("AccessGuard", "Authorization service",
         "RBAC/ABAC/reBAC APIs. AccessGuard stops hand-rolled permissions.",
         "Policy as code", "Audit logs", "Decision logs"),
        ("AuditTrail", "Tamper-evident audit logs",
         "Append-only logs with cryptographic verification. AuditTrail is SOC 2 gold.",
         "Cryptographic verify", "Searchable", "Exportable"),
        ("VulnScan", "Vulnerability scanner",
         "Scan code + infra for CVEs. VulnScan replaces Snyk for small teams.",
         "CVE database", "Auto-PR fixes", "Slack alerts"),
        ("PenTestAI", "AI penetration testing",
         "Continuous AI-driven pen tests. PenTestAI finds what humans miss.",
         "Automated recon", "Exploit suggestions", "Reports"),
        ("EndpointShield", "Endpoint detection",
         "EDR for SMBs without the price tag. EndpointShield catches ransomware.",
         "Behavioral detection", "Ransomware rollback", "Multi-OS"),
        ("PhishBlock", "Phishing protection",
         "Train employees + block phishing emails. PhishBlock cuts click rate 80%.",
         "Simulated attacks", "Email filtering", "Reporting"),
        ("ComplianceOS", "Compliance automation",
         "SOC 2 / ISO 27001 / HIPAA in one platform. ComplianceOS is Drata for SMBs.",
         "Multi-framework", "Evidence collection", "Auditor portal"),
        ("DataLoss", "DLP for SaaS",
         "Detect sensitive data in Slack/GDrive/Notion. DataLoss prevents leaks.",
         "Content scanning", "Policy engine", "Incident response"),
        ("Backuply", "Cloud backup",
         "Backup Slack/GDrive/Notion with one click. Backuply is insurance.",
         "One-click backup", "Point-in-time restore", "Compliance archive"),
        ("NetworkMap", "Network visualization",
         "Auto-discover and map your network. NetworkMap finds shadow IT.",
         "Asset discovery", "Topology maps", "Risk scoring"),
        ("CodeScan", "SAST for repos",
         "Scan code on every PR. CodeScan catches issues before merge.",
         "PR scanning", "Auto-fix suggestions", "Custom rules"),
        ("DepCheck", "Dependency scanner",
         "Detect vulnerable deps and outdated packages. DepCheck updates them.",
         "Auto-PR updates", "License checks", "Slack alerts"),
        ("SecretScan", "Secret leak detection",
         "Scan git history for leaked secrets. SecretScan rotates them.",
         "Git scanning", "Auto-rotation", "Alert routing"),
        ("IdentityHub", "Workforce identity",
         "SSO + provisioning + lifecycle. IdentityHub is Okta for SMBs.",
         "Lifecycle management", "Group sync", "MFA enforcement"),
        ("ConsentMgr", "Consent management",
         "Cookie/consent/privacy preference center. ConsentMgr is GDPR-ready.",
         "Multi-jurisdiction", "Preference center", "Audit trail"),
        ("BreachWatch", "Breach detection",
         "Dark-web monitoring for credentials. BreachWatch alerts + rotates.",
         "Dark-web scan", "Auto-rotation", "Affected-user alerts"),
        ("ThreatIntel", "Threat intelligence feed",
         "Curated IOCs and TTPs. ThreatIntel keeps your SOC current.",
         "Curated feeds", "STIX/TAXII", "SIEM integration"),
        ("ZeroTrust", "Zero-trust network access",
         "ZTNA without hardware. ZeroTrust is Cloudflare Access for SMBs.",
         "Identity-based access", "No hardware", "Audit logs"),
    ] * 5),  # 100 apps

    ("Integration Tools", [
        ("FlowMate", "Visual iPaaS",
         "Drag-drop integrations between 500+ apps. FlowMate replaces Zapier for SMBs.",
         "Visual builder", "500+ connectors", "Error handling"),
        ("WebhookPro", "Webhook router",
         "Receive, filter, transform, replay webhooks. WebhookPro handles vendor chaos.",
         "Smart routing", "Retry logic", "Replay tools"),
        ("APIBridge", "API-to-API translator",
         "Map fields between APIs. APIBridge ships legacy integrations fast.",
         "Field mapping", "Transform engine", "Versioning"),
        ("ETLConnect", "iPaaS for engineers",
         "Code-first integrations. ETLConnect replaces Workato for devs.",
         "Code-first", "Git-ops deploys", "TypeScript SDK"),
        ("SyncMaster", "Two-way sync engine",
         "Bi-directional sync between CRM/helpdesk/billing. SyncMaster handles conflicts.",
         "Conflict resolution", "Field mapping", "Real-time + batch"),
        ("PipeStream", "Streaming ETL",
         "Real-time CDC + streaming transforms. PipeStream is Kafka for SMBs.",
         "CDC streams", "Windowed aggregations", "Schema registry"),
        ("FormBridge", "Form-to-app bridge",
         "Route form submissions to 100+ apps. FormBridge is Typeform + Zapier.",
         "Form builder", "Conditional logic", "App routing"),
        ("DataSync", "Database-to-SaaS sync",
         "Mirror Postgres to CRM/marketing. DataSync keeps systems in lockstep.",
         "CDC-based", "Conflict resolution", "Audit logs"),
        ("OAuthKit", "OAuth integration toolkit",
         "Drop-in OAuth for 50+ APIs. OAuthKit ships third-party integrations fast.",
         "Token refresh", "Scope management", "Audit logs"),
        ("EventRouter", "Event router for SaaS",
         "Route events to subscribers with filters. EventRouter is Segment for SMBs.",
         "Event schemas", "Replay capability", "Multi-destination"),
        ("TransformEngine", "Field transformation",
         "Visual mapper with code escape hatch. TransformEngine maps any format.",
         "Visual + code", "Type coercion", "Schema validation"),
        ("ScheduleSync", "Scheduled data sync",
         "Cron-based syncs between apps. ScheduleSync is the simplest iPaaS.",
         "Cron UI", "Failure alerts", "Retry policy"),
        ("FileMove", "File transfer automation",
         "SFTP/S3/GDrive file syncs. FileMove replaces MOVEit for SMBs.",
         "Multi-protocol", "Encryption", "Audit logs"),
        ("MailParse", "Email-to-data",
         "Parse incoming emails into structured data. MailParse turns inbox into API.",
         "Attachment parsing", "Header extraction", "Webhook output"),
        ("LeadRoute", "Lead routing engine",
         "Round-robin, skills-based, geo-routing. LeadRoute maximizes conversions.",
         "Multi-rule", "Real-time", "Conversion analytics"),
        ("ContactSync", "Contact sync",
         "Two-way sync between address books. ContactSync ends contact chaos.",
         "Conflict resolution", "Field mapping", "Identity resolution"),
        ("CalSync", "Calendar sync",
         "Two-way Google/Outlook/iCloud sync. CalSync keeps calendars aligned.",
         "Multi-provider", "Conflict resolution", "Free-busy sharing"),
        ("FileWebhook", "File-system webhooks",
         "Trigger on S3/local file events. FileWebhook is event-driven automation.",
         "S3 events", "Local fs events", "Retry logic"),
        ("Restify", "REST API wrapper",
         "Wrap SOAP/GraphQL/gRPC as REST. Restify unifies legacy APIs.",
         "Auto-discovery", "Auth handling", "Caching"),
        ("GraphBridge", "GraphQL gateway",
         "Federate GraphQL APIs. GraphBridge unifies your API mesh.",
         "Schema federation", "Persisted queries", "Rate limiting"),
    ] * 5),  # 100 apps

    ("Voice/Audio", [
        ("PodcastAI", "AI podcast production",
         "Record, edit, and publish with AI assistance. PodcastAI is Descript for SMBs.",
         "AI editing", "Auto-transcription", "Distribution"),
        ("VoiceClone", "Voice cloning platform",
         "Clone voices with consent + watermarking. VoiceClone is ethical ElevenLabs.",
         "Consent flows", "Watermarking", "Quality scoring"),
        ("AudioBook", "Audiobook generator",
         "Convert manuscripts to audiobooks. AudioBook ships audiobooks in days.",
         "Multi-voice", "Chapter detection", "ACX export"),
        ("MusicMaker", "Royalty-free music AI",
         "Generate background music for videos. MusicMaker is Epidemic Sound for SMBs.",
         "Stem export", "Mood library", "License clarity"),
        ("SoundEffect", "SFX generator",
         "Generate sound effects on demand. SoundEffect is Freesound + AI.",
         "Prompt-based", "Library mode", "WAV export"),
        ("PodcastTrans", "Podcast transcription",
         "Transcribe + chapter + clip. PodcastTrans turns audio into content.",
         "Speaker ID", "Chapter detection", "Viral clip extraction"),
        ("VoiceMemo", "Voice memo organizer",
         "Capture, transcribe, search voice memos. VoiceMemo is Otter for individuals.",
         "Mobile capture", "Full-text search", "Calendar linking"),
        ("AudioClean", "Audio cleanup",
         "Remove noise, echo, filler words. AudioClean is Adobe Podcast for cheap.",
         "Noise removal", "Filler-word removal", "Batch mode"),
        ("RadioAI", "AI radio host",
         "Generate 24/7 radio stations from a topic. RadioAI is infinite music + talk.",
         "Multi-host voices", "News integration", "Schedule programming"),
        ("VoiceOver", "Voiceover generator",
         "Studio-quality voiceover in any language. VoiceOver replaces voice actors.",
         "Multi-language", "Emotion control", "Studio quality"),
        ("SongCover", "AI song covers",
         "Generate song covers in any voice (with consent). SongCover is for creators.",
         "Consent tracking", "Multi-voice", "Stem separation"),
        ("MeetingRec", "Meeting recorder",
         "Record, transcribe, summarize meetings. MeetingRec is Fireflies for SMBs.",
         "Auto-join", "Action items", "CRM sync"),
        ("LectureAI", "Lecture capture",
         "Record lectures, generate study guides. LectureAI is for educators.",
         "Auto-chapter", "Quiz generation", "Student sharing"),
        ("VoicemailAI", "Voicemail transcription",
         "Transcribe voicemails, route them, reply by text. VoicemailAI for sales.",
         "Real-time alerts", "Smart routing", "CRM logging"),
        ("CallCenterAI", "Call center AI",
         "Real-time agent assist for calls. CallCenterAI boosts conversion 20%.",
         "Live coaching", "Sentiment tracking", "Auto-summary"),
        ("PodcastAds", "Podcast ad marketplace",
         "Buy/sell podcast ads with measurement. PodcastAds replaces manual insertion.",
         "Dynamic insertion", "Attribution", "Self-serve buying"),
        ("VoiceGame", "Voice game engine",
         "Build voice games with branching dialog. VoiceGame is for Alexa/Discord.",
         "Branching editor", "Multi-platform", "Analytics"),
        ("AudioSearch", "Audio search engine",
         "Search inside audio/video files. AudioSearch turns media into knowledge.",
         "Timestamp results", "Topic clustering", "Snippet playback"),
        ("SpeechAnalytics", "Speech analytics",
         "Track talk time, sentiment, topics across calls. SpeechAnalytics for QA.",
         "Talk-time analytics", "Topic detection", "QA scorecards"),
        ("VoiceAuth", "Voice biometric auth",
         "Authenticate users by voice. VoiceAuth replaces passwords for phone apps.",
         "Anti-spoofing", "Multi-language", "Liveness checks"),
    ] * 5),  # 100 apps

    ("Video/Media", [
        ("VideoEditor", "AI video editor",
         "Cut, caption, reframe with AI. VideoEditor is CapCut for SMBs.",
         "Auto-reframe", "Auto-captions", "B-roll insertion"),
        ("ClipGen", "Short-clip generator",
         "Turn long videos into viral shorts. ClipGen is for content creators.",
         "Hook detection", "Auto-subtitles", "Multi-platform export"),
        ("ScreenRec", "Screen recorder + AI",
         "Record, transcribe, summarize screen recordings. ScreenRec is Loom + AI.",
         "Web recorder", "Auto-summary", "Engagement analytics"),
        ("WebinarAI", "AI webinar platform",
         "Run webinars with auto-replay + clips. WebinarAI replaces ZoomWebinar.",
         "Auto-clips", "Replay pages", "Engagement scoring"),
        ("VideoHost", "Video hosting + player",
         "Fast, branded video player. VideoHost is Wistia for SMBs.",
         "Custom player", "CDN delivery", "Engagement heatmaps"),
        ("LiveStream", "Live streaming platform",
         "Multi-platform simulcast. LiveStream is Restream for SMBs.",
         "Multi-destination", "Chat aggregation", "Stream health"),
        ("ThumbTester", "Thumbnail A/B testing",
         "Test YouTube thumbnails with real users. ThumbTester beats TubeBuddy.",
         "Multi-variant", "CTR prediction", "Audience targeting"),
        ("SubtitleAI", "Auto-subtitle service",
         "Multi-language subtitles with timing. SubtitleAI is for global creators.",
         "100+ languages", "Style control", "SRT/VTT export"),
        ("VideoTranslate", "Video dubbing AI",
         "Translate + lip-sync videos. VideoTranslate is for global content.",
         "Lip-sync", "Voice cloning", "Quality review"),
        ("GreenScreen", "AI green screen",
         "Remove background without a studio. GreenScreen is for video podcasts.",
         "Real-time", "Multi-subject", "Custom backgrounds"),
        ("VideoStock", "Stock video library",
         "Curated stock footage with AI search. VideoStock is Artgrid for SMBs.",
         "AI search", "Curated collections", "License clarity"),
        ("VODPlatform", "Video-on-demand platform",
         "Netflix-style site for your content. VODPlatform is Uscreen for SMBs.",
         "DRM support", "Paywall", "Recommendations"),
        ("VideoMeeting", "Async video updates",
         "Record video updates instead of meetings. VideoMeeting is for remote teams.",
         "Async by default", "Threaded replies", "Transcripts"),
        ("WebcamAI", "Webcam enhancer",
         "Studio-quality webcam with AI. WebcamAI is NVIDIA Broadcast for all.",
         "Auto-framing", "Lighting fix", "Background blur"),
        ("VideoAnalytics", "Video engagement analytics",
         "Heatmaps, drop-off, segment analytics. VideoAnalytics replaces Wistia.",
         "Heatmaps", "Drop-off alerts", "Segment reports"),
        ("AnimationAI", "AI animation studio",
         "Animate stills, generate motion graphics. AnimationAI is for marketers.",
         "Image-to-video", "Text-to-video", "Template library"),
        ("VideoAds", "Video ad builder",
         "Generate video ads from product URLs. VideoAds is for DTC brands.",
         "URL-to-video", "Multi-format", "A/B testing"),
        ("DocuVideo", "Documentary maker",
         "Turn interviews into mini-docs. DocuVideo is for journalism.",
         "Auto-edit", "B-roll library", "Captioning"),
        ("VideoCMS", "Video content management",
         "Organize, tag, search video library. VideoCMS is Frame.io for SMBs.",
         "AI tagging", "Approval workflow", "Review links"),
        ("LiveShop", "Live shopping platform",
         "Stream + sell simultaneously. LiveShop is for ecommerce brands.",
         "Product overlay", "Cart integration", "Chat commerce"),
    ] * 5),  # 100 apps
]

# Build apps list
APPS_900 = []
for category, templates in CATEGORY_TEMPLATES:
    for i, tpl in enumerate(templates):
        # Each category has 5 copies of 20 templates = 100 apps
        # Differentiate by appending year/edition
        copy_num = (i // 20) + 1
        name_base = tpl[0]
        if copy_num > 1:
            name = f"{name_base} {['Pro','Studio','Labs','Cloud','Plus'][copy_num-2]}"
        else:
            name = name_base
        tagline = tpl[1]
        desc = tpl[2]
        f1 = tpl[3]
        f2 = tpl[4]
        f3 = tpl[5]
        persona = "Operator"
        APPS_900.append((name, category, tagline, desc, f1, f2, f3, persona))

print(f"Generated {len(APPS_900)} additional apps.")

# Generate full-stack for all 900
def main():
    for app in APPS_900:
        name = app[0]
        slug = name.lower().replace(" ", "-")
        base = BASE / slug
        base.mkdir(exist_ok=True)
        files = build(app)
        # Add category-specific spec README, SPEC, ARCHITECTURE, API, DB_SCHEMA only if not exists
        spec_files_dir = base
        for path, content in files.items():
            fp = base / path
            fp.parent.mkdir(parents=True, exist_ok=True)
            if not fp.exists():
                fp.write_text(content, encoding="utf-8")
    print(f"Generated full-stack for {len(APPS_900)} additional apps.")


if __name__ == "__main__":
    main()
